# Generated by Django 3.0.8 on 2020-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_order_date_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='is_in_graphics',
            new_name='is_in_color',
        ),
    ]
