# Generated by Django 3.0.8 on 2020-08-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200830_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='is_in_abstracts',
            new_name='is_in_graphics',
        ),
    ]
