# Generated by Django 3.0.8 on 2020-11-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200830_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('u', 'Undefined Price'), ('r', 'Reserved'), ('s', 'Sold'), ('n', 'NotForSale')], default='a', max_length=1),
        ),
    ]
