# Generated by Django 3.0.8 on 2020-11-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201108_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(default='Some Text Here', max_length=1000),
            preserve_default=False,
        ),
    ]
