# Generated by Django 3.1.3 on 2020-11-12 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20201112_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
