# Generated by Django 3.1.3 on 2021-06-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210606_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_name',
            field=models.CharField(default='link', max_length=100),
            preserve_default=False,
        ),
    ]
